openapi: 3.0.0
info:
  title: ListingAPI
  description: The Listing API
  contact:
    name: AVIV
  version: "1.0"
servers:
  - url: /
    description: The Listing API
tags:
  - name: listings
    description: Listings operations
paths:
  /listings:
    get:
      summary: Get all listings
      description: Get all the listings registered in the app.
      tags:
        - listings
      operationId: get-listings
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Listing"
    post:
      summary: Create a listing
      description: Create a listing.
      tags:
        - listings
      operationId: post-listings
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity (WebDAV)
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListingWrite"
  "/listings/{id}":
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The ID of the listing to update.
    put:
      summary: Update a listing
      description: Update a listing described by its identifier.
      tags:
        - listings
      operationId: upsert-listing
      deprecated: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListingWrite"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
    patch:
      summary: Partially update a listing
      description: Update specific fields of a listing without replacing the entire resource.
      tags:
        - listings
      operationId: patch-listing
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListingPatch"
      responses:
        "200":
          description: Listing updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
        "404":
          description: Listing not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"
  "/listings/{id}/prices":
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The ID of the listing to get price history from.
    get:
      summary: Get listing price history
      description: Get the price history of a listing
      tags:
        - listings
      operationId: get-listing-prices
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Price"
components:
  schemas:
    Listing:
      allOf:
        - $ref: "#/components/schemas/ListingRead"
        - $ref: "#/components/schemas/ListingWrite"
    ListingRead:
      type: object
      description: Read-only fields of the listing model
      required:
        - id
        - created_date
        - updated_date
      properties:
        id:
          description: The unique identifier for the listing.
          type: integer
        created_date:
          description: The creation date of the listing.
          type: string
          format: date-time
        updated_date:
          description: The last update date of the listing.
          type: string
          format: date-time
    ListingWrite:
      type: object
      required:
        - name
        - postal_address
        - description
        - building_type
        - latest_price_eur
        - surface_area_m2
        - rooms_count
        - bedrooms_count
      properties:
        name:
          type: string
        postal_address:
          $ref: "#/components/schemas/PostalAddress"
        description:
          type: string
        building_type:
          type: string
          enum:
            - STUDIO
            - APARTMENT
            - HOUSE
        latest_price_eur:
          type: number
        surface_area_m2:
          type: number
        rooms_count:
          type: integer
        bedrooms_count:
          type: integer
        contact_phone_number:
          type: string
    ListingPatch:
      type: object
      properties:
        name:
          type: string
        postal_address:
          $ref: "#/components/schemas/PostalAddress"
        description:
          type: string
        building_type:
          type: string
          enum:
            - STUDIO
            - APARTMENT
            - HOUSE
        latest_price_eur:
          type: number
        surface_area_m2:
          type: number
        rooms_count:
          type: integer
        bedrooms_count:
          type: integer
        contact_phone_number:
          type: string
    PostalAddress:
      type: object
      required:
        - street_address
        - postal_code
        - city
        - country
      properties:
        street_address:
          type: string
        postal_code:
          type: string
        city:
          type: string
        country:
          type: string
          minLength: 2
          maxLength: 2
    Price:
      type: object
      properties:
        price_eur:
          type: number
        created_date:
          type: string
          format: date-time
    APIError:
      type: object
      properties:
        message:
          type: string
